spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #mysql驱动8.x版本使用com.mysql.cj.jdbc.Driver
    #5.x使用com.mysql.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    #数据库地址
    url: jdbc:mysql://127.0.0.1:3306/db_ee_server?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useAffectedRows=true
    #数据库账号
    username: root
    #数据库密码
    password: 123456
    #hikari连接池
    hikari:
      #2*cpu
      maximum-pool-size: 16
      #cpu
      minimum-idle: 8
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true