spring:
  application:
    name: equipment-service
    version: '@project.version@'
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/static/,classpath*:/META-INF/resources/
#日志
logging:
  config: classpath:META-INF/logback-${spring.profiles.active}.xml
  file:
    #框架logback中使用了以下配置
    max-size: 50MB
    max-history: 3
server:
  undertow:
    accesslog:
      dir: ./logs
      enabled: true
      prefix: ${spring.application.name}
  # 启动端口
  port: 9090
  servlet:
    context-path: /${spring.application.name}


#swagger
bt:
  swagger:
    title: ${spring.application.name}
    description: 电子设备平台
    version: ${spring.application.version}


#Mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.dcone.equipment_service.common.model.po